### ISSUE TITLE
version check of cherrypy says: 10.0.0 "is too old"

### ISSUE THREAD

**Issue by heddmorf** [devsnd/cherrymusic#654]
[cherrypy v10.0.0](github.com/cherrypy/cherrypy/releases) was released 2017-01-20 (15 days ago).

Fresh install of cherrypy from pip with python 2.7.12 (on ubuntu 16.04 LTS on x86_64).
cherrymusic from master trunk, v0.38.0

first run (and subsequent runs) produce the following:
```bash
$ python ./cherrymusic

cherrypy version is too old!
Current version: 10.0.0
Required version: 3 or higher
```

**Comment by heddmorf** [comment]
fixed by @tilboerner in Devel branch in commit f001b3661cccae0325a1c1b83be807bb7a6283a9

I'm new to this project... do you want this bug closed now, or wait until the fix is propagated to main branch?

**Comment by devsnd** [comment]
Hey @heddmorf,

Thanks for your report! I have marked this issue as `fixed in devel` and I'll close it once a new version is out.

**Comment by cmorgenstern** [comment]
Still seeing this issue.
cherrypy install via Arch Linux --> python-cherrypy 8.9.1-1

Crops up with AUR install --> [cherrymusic-devel-git](https://aur.archlinux.org/packages/cherrymusic-devel-git/)

Also crops up with fresh git pull:

```
git clone --branch devel https://github.com/devsnd/cherrymusic.git
cd cherrymusic/
python cherrymusic

cherrypy version is too old!
Current version: unknown
Required version: 3 or higher
```

Looks like the query for the version is returning the 'unknown' string:

```
python
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cherrypy;
>>> str(cherrypy.__version__).split('.', 1)[0]
'unknown'
```

I've temporarily solved the problem by removing the cherrypy version check from cherrymusicserver/__init__.py, but would appreciate a more durable solution so that I can utilize the Arch Linux AUR build for ease of updating via package manager in the future. Let me know if you would like me to provide any further information. Thanks!

**Comment by devsnd** [comment]
Hey Charles, thanks for your report.

Unfortunately, i cannot reproduce your issue. I've installed cherrymusic-devel-git from the AUR and used the cherrypy package from the Arch repositories.

I could however reproduce it if I had a stale cherrypy version laying around in the cherrymusic folder, which did override the system-wide installed one. That cherrypy version could then in turn not determine its own version (as it parses its version from another location it seems, which could not be found).

Anyway, I will change the code so that an undetected version will not prohibit the server from starting.

**Comment by devsnd** [comment]
I have created a fix an released a new version, 0.40.0. Please try it out and report back if your issues persist!

Thanks for your help! 🧀

**Comment by cmorgenstern** [comment]
That looks to have solved it. Building from the AUR with [cherrymusic-devel-git](https://aur.archlinux.org/packages/cherrymusic-devel-git/) now completes without issue. Thank you for making the adjustment.
