### ISSUE TITLE
No playback (formatTime is not a function)

### ISSUE THREAD

**Issue by Aanok** [devsnd/cherrymusic#698]
CherryMusic 0.41 running on Debian 9, Python 3.5.3, accessed from Chromium 61.0.3163.100.

The server boots and a webclient can connect and navigate the library. When clicking on a track to add it to the queue, however, the red label "1/1 remaining tracks" gets stuck and nothing is added to the queue.

Version 0.40 works fine.

Below are a console log and my config.

[192.168.1.29-1507649950410.log.txt](https://github.com/devsnd/cherrymusic/files/1372524/192.168.1.29-1507649950410.log.txt)
[cherrymusic.conf.txt](https://github.com/devsnd/cherrymusic/files/1372532/cherrymusic.conf.txt)

**Comment by devsnd** [comment]
Hey @Aanok thanks for your bug report. I messed up the release, sorry!
I have just released a new version 0.41.1 that should fix these issues!

Thanks again for the report and your patience 🦅

**Comment by MasterGroosha** [comment]
Well, I'm on 0.41.1 and still have this issue :(
![image](https://user-images.githubusercontent.com/2780044/31788149-8c53a372-b516-11e7-83ab-7eb3e48ae043.png)

**Comment by devsnd** [comment]
Hey @MasterGroosha 

Can you please try to empty your browser cache?
Also, where did you download the update from? github / website / pypi / linux package?

**Comment by MasterGroosha** [comment]
I'm pretty sure I installed it from Github. It was 100% the latest version 0.41.1.
Then I got this errors and reported to you. The only "custom" thing I did was to setup CherryPy behind Nginx with SSL.  
Right now I cloned the repo to another folder and force copied new files over the old ones. Now CherryMusic is working fine o_O

I really don't know why this inconsistency happeded, anyway, sorry for taking your time. Now it's working.

**Comment by devsnd** [comment]
No problem. Maybe it was cached in nginx?

**Comment by MasterGroosha** [comment]
That would be strange: I don't remember installing any CherryMusic version ever on that machine.

I'm going to deploy one more CherryMusic next week on another "clean" server, and I'll let you know if I'll face the same issue.

**Comment by SkylerWilliams** [comment]
Any news on this? I am having the same issue: CherryMusic 0.41.1, Gentoo 2.4.1, Python 2.7.14, all browsers
